name: copycat_base
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/raj457036/copycat_base

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  isar: 3.1.0+1
  isar_flutter_libs: 3.1.0+1
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  universal_io: ^2.2.2
  win32_registry: ^1.1.3
  image: ^4.2.0
  blurhash_dart: ^1.2.1
  easy_worker: ^1.0.1
  timeago: ^3.7.0
  dartz: ^0.10.1
  googleapis: ^13.1.0
  super_clipboard: ^0.8.17
  clipboard_watcher: ^0.2.1
  window_manager: ^0.3.9
  rxdart: ^0.27.5
  file_picker: ^8.0.5
  encrypt: ^5.0.3
  hotkey_manager: ^0.2.3
  path_provider: ^2.1.3
  path: ^1.9.0
  uuid: ^4.4.2
  atom_event_bus: ^0.0.5
  logger: ^2.4.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  mime: ^1.0.5
  http: ^1.2.2
  intl: ^0.19.0
  

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  isar_generator: 3.1.0+1
  freezed: 2.4.7
  json_serializable: ^6.7.1

dependency_overrides:
  intl: ^0.19.0
  analyzer: ^6.4.1

flutter: